server:
  port: 8080  # Te sugiero 8080 o 9090, el 443 requiere permisos de admin y certificados SSL

spring:
  cloud:
    gateway:
      # CONFIGURACIÓN DEL DISCOVERY LOCATOR (CORREGIDA)
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
      
      # CONFIGURACIÓN DE FILTROS (CORREGIDA)
      default-filters:
        - name: RewritePath
          args:
            regexp: "^/.*?/(?<remaining>.*)$"
            replacement: "/${remaining}"

# CONEXIÓN A EUREKA
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true # Recomendado para microservicios locales