spring:
  application:
     name: pokemon4-service 
# 1. Configuración de Puerto Dinámico (Clave para Múltiples Instancias)
server: 
  port: 0 
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # 3. ID de instancia única para diferenciar las copias en Eureka
    # Se usa el nombre de la app junto con un valor aleatorio.
    instance-id: ${spring.application.name}:${random.value}